
version: "3"

services:
  books_mysql:
    container_name: libros
    image: mysql:8.0
    ports:
      - 3360:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db-data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]

volumes:
  db-data: